WebManager/WebManager/Controllers/UsersAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using WebManager.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using WebManager.Models.AccountViewModels;
using Microsoft.AspNetCore.Authorization;

namespace WebManager.Controllers
{
    public class UsersAdminController : Controller
    {
        UserManager<ApplicationUser> _userManager;
        RoleManager<IdentityRole> _roleManager;

        public UsersAdminController(UserManager<ApplicationUser> manager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = manager;
            _roleManager = roleManager;
        }

        #region UserRegion
        [Authorize(Roles = "admin")]
        public IActionResult Index() => View(_userManager.Users.ToList());


        [Authorize(Roles ="admin")]
        public IActionResult Create() => View();

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser { Email = model.Email, UserName = model.Name };
                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    throw new Exception();
                }
            }
            return View();
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var model = new UserViewModel()
                {
                    Id = user.Id,
                    Email = user.Email,
                    Name = user.UserName,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }
            return NotFound();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Name;

                    var userRoles = await _userManager.GetRolesAsync(user);
                    var allRoles = _roleManager.Roles.ToList();
                    var addedRoles = model.UserRoles.Except(userRoles);
                    var removedRoles = userRoles.Except(model.UserRoles);
                    await _userManager.AddToRolesAsync(user, addedRoles);
                    await _userManager.RemoveFromRolesAsync(user, removedRoles);

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);
            }

            return RedirectToAction("Index");
        }
        #endregion UserRegion

        #region RoleRegion
        [Authorize(Roles = "admin")]
        public IActionResult RoleList() => View(_roleManager.Roles.ToList());

        [Authorize(Roles = "admin")]
        public IActionResult CreateRole() => View();

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateRole(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("RoleList");
                }
                else
                {
                    new Exception();
                }
            }
            return View(name);
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            return View(role);
        }

        [HttpPost, ActionName("DeleteRole")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> RoleDeleteConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("RoleList");
        }

        #endregion RoleRegion
    }
}

WebManager/WebManager/Views/UsersAdmin/Create.cshtml
@model WebManager.Models.AccountViewModels.UserViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<form asp-action="Create" asp-controller="UsersAdmin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="control-label">Password</label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>

</form>

<div>
    <a asp-action="Index">Back to List Users</a>
</div>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebManager/WebManager/Views/UsersAdmin/CreateRole.cshtml
@model string
    @{
        ViewData["Title"] = "CreateRole";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>CreateRole</h2>


<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="CreateRole" method="post">
    <div class="form-group">
        <label for="name">New role</label>
        <input name="name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-default">Save</button>
</form>

<div>
    <a asp-action="Index">Back to List Users</a>
</div>

WebManager/WebManager/Views/UsersAdmin/Delete.cshtml
@model WebManager.Models.ApplicationUser
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List Users</a>
        </div>
    </form>
</div>

WebManager/WebManager/Views/UsersAdmin/DeleteRole.cshtml
@model Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole
@{
    ViewData["Title"] = "DeleteRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteRole</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="Id" />
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>        
    </dl>

    <form asp-action="DeleteRole">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="RoleList">Back to List Role</a>
        </div>
    </form>
</div>

WebManager/WebManager/Views/UsersAdmin/Edit.cshtml
@model WebManager.Models.AccountViewModels.UserViewModel
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<form asp-action="Edit" asp-controller="UsersAdmin">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="Password" />
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label">Email</label>
        <input type="text" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        @foreach (IdentityRole role in Model.AllRoles)
        {
            <input type="checkbox" name="UserRoles" value="@role.Name"
                   @(Model.UserRoles.Contains(role.Name) ? "checked=\"checked\"" : "") />@role.Name <br/>
        }
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</form>   
    

<div>
    <a asp-action="Index">Back to List Users</a>
</div>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebManager/WebManager/Views/UsersAdmin/Index.cshtml
@model IEnumerable<WebManager.Models.ApplicationUser>
@{
    ViewData["Title"] = "Users List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Users List</h2>

<a asp-action="Create">Add user</a>
<a style="padding: 5px 10px"></a>
<a asp-action="CreateRole">Add role</a>
<a style="padding: 5px 10px"></a>
<a asp-action="RoleList">View roles list</a>


<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Email
        </th>
    </tr>
    @foreach (var user in Model)
            {
        <tr>
            <td>@user.UserName</td>
            <td>@user.Email</td>
            <td>
                <a asp-action="Edit" asp-route-id="@user.Id">Edit</a>
                <a asp-action="Delete" asp-route-id="@user.Id">Delete</a>
            </td>
        </tr>
    }
</table>

WebManager/WebManager/Views/UsersAdmin/RoleList.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityRole>
@{
    ViewData["Title"] = "RoleList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RoleList</h2>
<a asp-action="CreateRole">Add role</a>
<table>
    <tr>
        <th>
            Role
        </th>
        <th>
        </th>
    </tr>
    @foreach (var role in Model)
            {
        <tr>
            <td>@role.Name</td>
            <td><a asp-action="DeleteRole" asp-route-id="@role.Id">Delete</a></td>
        </tr>
    }
</table>